config/routes.rb
Rails.application.routes.draw do
  resources :frequencia

  resources :categoria

  resources :nichos

  resources :subcategoria

  resources :previsaos

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/previsao.rb
class Previsao < ActiveRecord::Base
  belongs_to :frequencia
end

app/controllers/previsaos_controller.rb
class PrevisaosController < ApplicationController
  before_action :set_previsao, only: [:show, :edit, :update, :destroy]

  # GET /previsaos
  # GET /previsaos.json
  def index
    @previsaos = Previsao.all
  end

  # GET /previsaos/1
  # GET /previsaos/1.json
  def show
  end

  # GET /previsaos/new
  def new
    @previsao = Previsao.new
  end

  # GET /previsaos/1/edit
  def edit
  end

  # POST /previsaos
  # POST /previsaos.json
  def create
    @previsao = Previsao.new(previsao_params)

    respond_to do |format|
      if @previsao.save
        format.html { redirect_to @previsao, notice: 'Previsao was successfully created.' }
        format.json { render :show, status: :created, location: @previsao }
      else
        format.html { render :new }
        format.json { render json: @previsao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /previsaos/1
  # PATCH/PUT /previsaos/1.json
  def update
    respond_to do |format|
      if @previsao.update(previsao_params)
        format.html { redirect_to @previsao, notice: 'Previsao was successfully updated.' }
        format.json { render :show, status: :ok, location: @previsao }
      else
        format.html { render :edit }
        format.json { render json: @previsao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /previsaos/1
  # DELETE /previsaos/1.json
  def destroy
    @previsao.destroy
    respond_to do |format|
      format.html { redirect_to previsaos_url, notice: 'Previsao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_previsao
      @previsao = Previsao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def previsao_params
      params.require(:previsao).permit(:previsao, :ativo, :frequencia_id)
    end
end

app/helpers/previsaos_helper.rb
module PrevisaosHelper
end

app/views/previsaos/_form.html.erb
<%= simple_form_for(@previsao) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :previsao %>
    <%= f.input :ativo %>
    <%= f.association :frequencia %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/previsaos/edit.html.erb
<h1>Editing previsao</h1>

<%= render 'form' %>

<%= link_to 'Show', @previsao %> |
<%= link_to 'Back', previsaos_path %>

app/views/previsaos/index.html.erb
<h1>Listing previsaos</h1>

<table>
  <thead>
    <tr>
      <th>Previsao</th>
      <th>Ativo</th>
      <th>Frequencia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @previsaos.each do |previsao| %>
      <tr>
        <td><%= previsao.previsao %></td>
        <td><%= previsao.ativo %></td>
        <td><%= previsao.frequencia %></td>
        <td><%= link_to 'Show', previsao %></td>
        <td><%= link_to 'Edit', edit_previsao_path(previsao) %></td>
        <td><%= link_to 'Destroy', previsao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Previsao', new_previsao_path %>

app/views/previsaos/new.html.erb
<h1>New previsao</h1>

<%= render 'form' %>

<%= link_to 'Back', previsaos_path %>

app/views/previsaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Previsao:</strong>
  <%= @previsao.previsao %>
</p>

<p>
  <strong>Ativo:</strong>
  <%= @previsao.ativo %>
</p>

<p>
  <strong>Frequencia:</strong>
  <%= @previsao.frequencia %>
</p>

<%= link_to 'Edit', edit_previsao_path(@previsao) %> |
<%= link_to 'Back', previsaos_path %>