config/routes.rb
Rails.application.routes.draw do
  resources :frequencia

  resources :categoria

  resources :nichos

  resources :subcategoria

  resources :previsaos

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/subcategoria.rb
class Subcategoria < ActiveRecord::Base
  belongs_to :categoria
end

app/controllers/subcategoria_controller.rb
class SubcategoriaController < ApplicationController
  before_action :set_subcategorium, only: [:show, :edit, :update, :destroy]

  # GET /subcategoria
  # GET /subcategoria.json
  def index
    @subcategoria = Subcategorium.all
  end

  # GET /subcategoria/1
  # GET /subcategoria/1.json
  def show
  end

  # GET /subcategoria/new
  def new
    @subcategorium = Subcategorium.new
  end

  # GET /subcategoria/1/edit
  def edit
  end

  # POST /subcategoria
  # POST /subcategoria.json
  def create
    @subcategorium = Subcategorium.new(subcategorium_params)

    respond_to do |format|
      if @subcategorium.save
        format.html { redirect_to @subcategorium, notice: 'Subcategorium was successfully created.' }
        format.json { render :show, status: :created, location: @subcategorium }
      else
        format.html { render :new }
        format.json { render json: @subcategorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subcategoria/1
  # PATCH/PUT /subcategoria/1.json
  def update
    respond_to do |format|
      if @subcategorium.update(subcategorium_params)
        format.html { redirect_to @subcategorium, notice: 'Subcategorium was successfully updated.' }
        format.json { render :show, status: :ok, location: @subcategorium }
      else
        format.html { render :edit }
        format.json { render json: @subcategorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcategoria/1
  # DELETE /subcategoria/1.json
  def destroy
    @subcategorium.destroy
    respond_to do |format|
      format.html { redirect_to subcategoria_url, notice: 'Subcategorium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcategorium
      @subcategorium = Subcategorium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subcategorium_params
      params.require(:subcategorium).permit(:subcategoria, :ativo, :categoria_id)
    end
end

app/helpers/subcategoria_helper.rb
module SubcategoriaHelper
end

app/views/subcategoria/_form.html.erb
<%= simple_form_for(@subcategorium) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :subcategoria %>
    <%= f.input :ativo %>
    <%= f.association :categoria %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/subcategoria/edit.html.erb
<h1>Editing subcategorium</h1>

<%= render 'form' %>

<%= link_to 'Show', @subcategorium %> |
<%= link_to 'Back', subcategoria_path %>

app/views/subcategoria/index.html.erb
<h1>Listing subcategoria</h1>

<table>
  <thead>
    <tr>
      <th>Subcategoria</th>
      <th>Ativo</th>
      <th>Categoria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subcategoria.each do |subcategorium| %>
      <tr>
        <td><%= subcategorium.subcategoria %></td>
        <td><%= subcategorium.ativo %></td>
        <td><%= subcategorium.categoria %></td>
        <td><%= link_to 'Show', subcategorium %></td>
        <td><%= link_to 'Edit', edit_subcategorium_path(subcategorium) %></td>
        <td><%= link_to 'Destroy', subcategorium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subcategorium', new_subcategorium_path %>

app/views/subcategoria/new.html.erb
<h1>New subcategorium</h1>

<%= render 'form' %>

<%= link_to 'Back', subcategoria_path %>

app/views/subcategoria/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subcategoria:</strong>
  <%= @subcategorium.subcategoria %>
</p>

<p>
  <strong>Ativo:</strong>
  <%= @subcategorium.ativo %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @subcategorium.categoria %>
</p>

<%= link_to 'Edit', edit_subcategorium_path(@subcategorium) %> |
<%= link_to 'Back', subcategoria_path %>