config/routes.rb
Rails.application.routes.draw do
  resources :frequencia

  resources :categoria

  resources :nichos

  resources :subcategoria

  resources :previsaos

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/frequencia.rb
class Frequencia < ActiveRecord::Base
  belongs_to :subcategoria
  has_many :previsaos
end

app/controllers/frequencia_controller.rb
class FrequenciaController < ApplicationController
  before_action :set_frequencium, only: [:show, :edit, :update, :destroy]

  # GET /frequencia
  # GET /frequencia.json
  def index
    @frequencia = Frequencium.all
  end

  # GET /frequencia/1
  # GET /frequencia/1.json
  def show
  end

  # GET /frequencia/new
  def new
    @frequencium = Frequencium.new
  end

  # GET /frequencia/1/edit
  def edit
  end

  # POST /frequencia
  # POST /frequencia.json
  def create
    @frequencium = Frequencium.new(frequencium_params)

    respond_to do |format|
      if @frequencium.save
        format.html { redirect_to @frequencium, notice: 'Frequencium was successfully created.' }
        format.json { render :show, status: :created, location: @frequencium }
      else
        format.html { render :new }
        format.json { render json: @frequencium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frequencia/1
  # PATCH/PUT /frequencia/1.json
  def update
    respond_to do |format|
      if @frequencium.update(frequencium_params)
        format.html { redirect_to @frequencium, notice: 'Frequencium was successfully updated.' }
        format.json { render :show, status: :ok, location: @frequencium }
      else
        format.html { render :edit }
        format.json { render json: @frequencium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frequencia/1
  # DELETE /frequencia/1.json
  def destroy
    @frequencium.destroy
    respond_to do |format|
      format.html { redirect_to frequencia_url, notice: 'Frequencium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frequencium
      @frequencium = Frequencium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def frequencium_params
      params.require(:frequencium).permit(:frequencia, :ativo, :subcategoria_id)
    end
end

app/helpers/frequencia_helper.rb
module FrequenciaHelper
end

app/views/frequencia/_form.html.erb
<%= simple_form_for(@frequencium) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :frequencia %>
    <%= f.input :ativo %>
    <%= f.association :subcategoria %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/frequencia/edit.html.erb
<h1>Editing frequencium</h1>

<%= render 'form' %>

<%= link_to 'Show', @frequencium %> |
<%= link_to 'Back', frequencia_path %>

app/views/frequencia/index.html.erb
<h1>Listing frequencia</h1>

<table>
  <thead>
    <tr>
      <th>Frequencia</th>
      <th>Ativo</th>
      <th>Subcategoria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @frequencia.each do |frequencium| %>
      <tr>
        <td><%= frequencium.frequencia %></td>
        <td><%= frequencium.ativo %></td>
        <td><%= frequencium.subcategoria %></td>
        <td><%= link_to 'Show', frequencium %></td>
        <td><%= link_to 'Edit', edit_frequencium_path(frequencium) %></td>
        <td><%= link_to 'Destroy', frequencium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Frequencium', new_frequencium_path %>

app/views/frequencia/new.html.erb
<h1>New frequencium</h1>

<%= render 'form' %>

<%= link_to 'Back', frequencia_path %>

app/views/frequencia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Frequencia:</strong>
  <%= @frequencium.frequencia %>
</p>

<p>
  <strong>Ativo:</strong>
  <%= @frequencium.ativo %>
</p>

<p>
  <strong>Subcategoria:</strong>
  <%= @frequencium.subcategoria %>
</p>

<%= link_to 'Edit', edit_frequencium_path(@frequencium) %> |
<%= link_to 'Back', frequencia_path %>