config/routes.rb
Rails.application.routes.draw do
  resources :frequencia

  resources :categoria

  resources :nichos

  resources :subcategoria

  resources :previsaos

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/nicho.rb
class Nicho < ActiveRecord::Base
  belongs_to :categoria
  has_many :categoria
end

app/controllers/nichos_controller.rb
class NichosController < ApplicationController
  before_action :set_nicho, only: [:show, :edit, :update, :destroy]

  # GET /nichos
  # GET /nichos.json
  def index
    @nichos = Nicho.all
  end

  # GET /nichos/1
  # GET /nichos/1.json
  def show
  end

  # GET /nichos/new
  def new
    @nicho = Nicho.new
  end

  # GET /nichos/1/edit
  def edit
  end

  # POST /nichos
  # POST /nichos.json
  def create
    @nicho = Nicho.new(nicho_params)

    respond_to do |format|
      if @nicho.save
        format.html { redirect_to @nicho, notice: 'Nicho was successfully created.' }
        format.json { render :show, status: :created, location: @nicho }
      else
        format.html { render :new }
        format.json { render json: @nicho.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nichos/1
  # PATCH/PUT /nichos/1.json
  def update
    respond_to do |format|
      if @nicho.update(nicho_params)
        format.html { redirect_to @nicho, notice: 'Nicho was successfully updated.' }
        format.json { render :show, status: :ok, location: @nicho }
      else
        format.html { render :edit }
        format.json { render json: @nicho.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nichos/1
  # DELETE /nichos/1.json
  def destroy
    @nicho.destroy
    respond_to do |format|
      format.html { redirect_to nichos_url, notice: 'Nicho was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nicho
      @nicho = Nicho.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nicho_params
      params.require(:nicho).permit(:nicho, :ativo, :categoria_id)
    end
end

app/helpers/nichos_helper.rb
module NichosHelper
end

app/views/nichos/_form.html.erb
<%= simple_form_for(@nicho) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nicho %>
    <%= f.input :ativo %>
    <%= f.association :categoria %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/nichos/edit.html.erb
<h1>Editing nicho</h1>

<%= render 'form' %>

<%= link_to 'Show', @nicho %> |
<%= link_to 'Back', nichos_path %>

app/views/nichos/index.html.erb
<h1>Listing nichos</h1>

<table>
  <thead>
    <tr>
      <th>Nicho</th>
      <th>Ativo</th>
      <th>Categoria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nichos.each do |nicho| %>
      <tr>
        <td><%= nicho.nicho %></td>
        <td><%= nicho.ativo %></td>
        <td><%= nicho.categoria %></td>
        <td><%= link_to 'Show', nicho %></td>
        <td><%= link_to 'Edit', edit_nicho_path(nicho) %></td>
        <td><%= link_to 'Destroy', nicho, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nicho', new_nicho_path %>

app/views/nichos/new.html.erb
<h1>New nicho</h1>

<%= render 'form' %>

<%= link_to 'Back', nichos_path %>

app/views/nichos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nicho:</strong>
  <%= @nicho.nicho %>
</p>

<p>
  <strong>Ativo:</strong>
  <%= @nicho.ativo %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @nicho.categoria %>
</p>

<%= link_to 'Edit', edit_nicho_path(@nicho) %> |
<%= link_to 'Back', nichos_path %>